name: aldiscore
channels:
- bioconda
- conda-forge
dependencies:
- python>=3.12
- biopython
- pandas
- numpy
- tqdm
- scipy
- pytest
- dotenv
# - notebook
# - pypythia[version='=1.2.1']
# - snakemake[version='>=8.9']
